import { Theme } from './ThemeContext';

export const defaultTheme: Theme = {
  colorScheme: 'light',
  palette: {
    default: {
      background: '#ffffff',
      backgroundLight: '#f7f7f7',
      text: '#333333',
      textLight: '#777777',
      textInverted: '#ffffff',
      link: '#0061f2',
      border: '#e0e0e0',
      borderDark: '#cccccc',
      icon: '#333333',
    },
    primary: {
      background: '#0070f3',
      backgroundLight: '#66aaff',
      text: '#ffffff',
      textLight: '#b3d7ff',
      textInverted: '#0070f3',
      link: '#ffffff',
      border: '#005bb5',
      borderDark: '#00449b',
      icon: '#ffffff',
    },
    secondary: {
      background: '#28a745',
      backgroundLight: '#66c67f',
      text: '#ffffff',
      textLight: '#b3ffb3',
      textInverted: '#28a745',
      link: '#ffffff',
      border: '#1c7c39',
      borderDark: '#155d2a',
      icon: '#ffffff',
    },
    inverted: {
      background: '#121212',
      backgroundLight: '#333333',
      text: '#ffffff',
      textLight: '#bbbbbb',
      textInverted: '#121212',
      link: '#0061f2',
      border: '#444444',
      borderDark: '#555555',
      icon: '#ffffff',
    },
    error: {
      background: '#f8d7da',
      backgroundLight: '#f5c6cb',
      text: '#721c24',
      textLight: '#f1f3f5',
      textInverted: '#ffffff',
      link: '#dc3545',
      border: '#f5c6cb',
      borderDark: '#c82333',
      icon: '#721c24',
    },
  },
};

export const darkTheme: Theme = {
  colorScheme: 'dark',
  palette: {
    default: {
      background: '#121212',
      backgroundLight: '#1e1e1e',
      text: '#e0e0e0',
      textLight: '#b0b0b0',
      textInverted: '#121212',
      link: '#0061f2',
      border: '#333333',
      borderDark: '#555555',
      icon: '#ffffff',
    },
    primary: {
      background: '#0070f3',
      backgroundLight: '#66aaff',
      text: '#ffffff',
      textLight: '#b3d7ff',
      textInverted: '#0070f3',
      link: '#ffffff',
      border: '#005bb5',
      borderDark: '#00449b',
      icon: '#ffffff',
    },
    secondary: {
      background: '#28a745',
      backgroundLight: '#66c67f',
      text: '#ffffff',
      textLight: '#b3ffb3',
      textInverted: '#28a745',
      link: '#ffffff',
      border: '#1c7c39',
      borderDark: '#155d2a',
      icon: '#ffffff',
    },
    inverted: {
      background: '#121212',
      backgroundLight: '#333333',
      text: '#ffffff',
      textLight: '#bbbbbb',
      textInverted: '#121212',
      link: '#0061f2',
      border: '#444444',
      borderDark: '#555555',
      icon: '#ffffff',
    },
    error: {
      background: '#f8d7da',
      backgroundLight: '#f5c6cb',
      text: '#721c24',
      textLight: '#f1f3f5',
      textInverted: '#ffffff',
      link: '#dc3545',
      border: '#f5c6cb',
      borderDark: '#c82333',
      icon: '#721c24',
    },
  },
};
